name: Build Check
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Build
        run: |
          make build/linux.o

      - name: Check format
        run: |
          make check-format
